<a href="https://colab.research.google.com/github/chaithanya21/Tensorflow-In-Practice/blob/master/DL_Assesment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==2.0.0

In [0]:
import tensorflow as tf


In [2]:
print(tf.__version__)

2.0.0


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:
from textblob import TextBlob
import pandas as pd
from textblob.sentiments import NaiveBayesAnalyzer

In [0]:
from textblob import TextBlob
from textblob.taggers import NLTKTagger
nltk_tagger = NLTKTagger()


In [32]:
import nltk
nltk.download('averaged_perceptron_tagger')
  

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [0]:
def tokenizer(Sentence,num_words=100,oov_token='OOV'):
  
  tokenizer=Tokenizer(num_words=num_words,oov_token=oov_token)
  tokenizer.fit_on_texts(Sentence)
  word_index=tokenizer.word_index
  print('\nword_index_of_Sentence:\n',word_index)
  Sequences=tokenizer.texts_to_sequences(Sentence)
  print('Sentences Encoded as the Sequence of Tokens:',Sequences)
  padded_seq=pad_sequences(Sequences,padding='post')
  print('\nThe Padded Sequence:\n',padded_seq)
  df = pd.DataFrame(columns = ['Line','Polarity', 'Subjectivity' ,'Sentiment','Classification'])
  blob=TextBlob(".\n".join(Sentence),analyzer=NaiveBayesAnalyzer(),pos_tagger=nltk_tagger)
  tags=blob.pos_tags
  DICT={}
  for a,b in tags:
    DICT.setdefault(a, []).append(b)
  print('Parts of Speech:',DICT)
  POS_dataframe=pd.DataFrame(tags,columns=['word','pos'])
  print(POS_dataframe.head(10))
  for sentence in blob.sentences:
    df.loc[len(df)] = [str(sentence),sentence.polarity, sentence.subjectivity,sentence.sentiment,sentence.sentiment.classification]
  return df
  
  
  

 
  

In [81]:
tokenizer(Sentence=['This is very bad','This is Very Good'],num_words=100,oov_token='<OOV>')


word_index_of_Sentence:
 {'<OOV>': 1, 'this': 2, 'is': 3, 'very': 4, 'bad': 5, 'good': 6}
Sentences Encoded as the Sequence of Tokens: [[2, 3, 4, 5], [2, 3, 4, 6]]

The Padded Sequence:
 [[2 3 4 5]
 [2 3 4 6]]
Parts of Speech: {'This': ['DT', 'DT'], 'is': ['VBZ', 'VBZ'], 'very': ['RB'], 'bad': ['JJ'], 'Very': ['RB'], 'Good': ['JJ']}
   word  pos
0  This   DT
1    is  VBZ
2  very   RB
3   bad   JJ
4  This   DT
5    is  VBZ
6  Very   RB
7  Good   JJ


Line  ...  Classification
0  This is very bad.  ...             neg
1  This is Very Good  ...             pos

[2 rows x 5 columns]

In [82]:
tokenizer(['Steve smith is the greatest test batsman of Modern test  Cricket','Virat is the best the ODI cricketer of the decade'])


word_index_of_Sentence:
 {'OOV': 1, 'the': 2, 'is': 3, 'test': 4, 'of': 5, 'steve': 6, 'smith': 7, 'greatest': 8, 'batsman': 9, 'modern': 10, 'cricket': 11, 'virat': 12, 'best': 13, 'odi': 14, 'cricketer': 15, 'decade': 16}
Sentences Encoded as the Sequence of Tokens: [[6, 7, 3, 2, 8, 4, 9, 5, 10, 4, 11], [12, 3, 2, 13, 2, 14, 15, 5, 2, 16]]

The Padded Sequence:
 [[ 6  7  3  2  8  4  9  5 10  4 11]
 [12  3  2 13  2 14 15  5  2 16  0]]
Parts of Speech: {'Steve': ['NNP'], 'smith': ['NN'], 'is': ['VBZ', 'VBZ'], 'the': ['DT', 'DT', 'DT', 'DT'], 'greatest': ['JJS'], 'test': ['NN', 'NN'], 'batsman': ['NN'], 'of': ['IN', 'IN'], 'Modern': ['NNP'], 'Cricket': ['NN'], 'Virat': ['NNP'], 'best': ['JJS'], 'ODI': ['NNP'], 'cricketer': ['NN'], 'decade': ['NN']}
       word  pos
0     Steve  NNP
1     smith   NN
2        is  VBZ
3       the   DT
4  greatest  JJS
5      test   NN
6   batsman   NN
7        of   IN
8    Modern  NNP
9      test   NN


Line  ...  Classification
0  Steve smith is the greatest test batsman of Mo...  ...             pos
1  Virat is the best the ODI cricketer of the decade  ...             pos

[2 rows x 5 columns]