<a href="https://colab.research.google.com/github/chaithanya21/Tensorflow-In-Practice/blob/master/Natural_Language_Processing_in_Tensorflow(Tokenizer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [0]:
sentences=['Steve Smith is the greatest Test Batsman of Modern Cricket',
           'Virat kohli is the greatest ODI Batsman of Modern cricket']

In [0]:
#Create an Instance of the tokenizer
tokenizer=Tokenizer(num_words= 1000 )

In [0]:
tokenizer.fit_on_texts(sentences)

In [0]:
word_index=tokenizer.word_index

In [31]:
print(word_index)

{'is': 1, 'the': 2, 'greatest': 3, 'batsman': 4, 'of': 5, 'modern': 6, 'cricket': 7, 'steve': 8, 'smith': 9, 'test': 10, 'virat': 11, 'kohli': 12, 'odi': 13}


In [0]:
#example two shows how keras Tokenizers ignores puctuations , Case sensitivity etc

Sentences=['i, love : my dogs', 'I love my DoG!']

In [0]:
tokeni_zer=Tokenizer(num_words=100)

In [0]:
tokeni_zer.fit_on_texts(Sentences)

In [0]:
WI=tokeni_zer.word_index

In [36]:
print(WI)

{'i': 1, 'love': 2, 'my': 3, 'dogs': 4, 'dog': 5}


In [0]:
# Using fit_to_texts and them embedding them as a set of sentences

App=['This app is really Nice','The App has lot of bug issues','It works fine']

In [0]:
Embedding=Tokenizer(num_words=100)

In [0]:
Embedding.fit_on_texts(App)

In [0]:
WI=Embedding.word_index

In [41]:
print(WI)

{'app': 1, 'this': 2, 'is': 3, 'really': 4, 'nice': 5, 'the': 6, 'has': 7, 'lot': 8, 'of': 9, 'bug': 10, 'issues': 11, 'it': 12, 'works': 13, 'fine': 14}


In [0]:
texts_to_Sequences=Embedding.texts_to_sequences(App)

In [49]:


print(texts_to_Sequences)

[[2, 1, 3, 4, 5], [6, 1, 7, 8, 9, 10, 11], [12, 13, 14]]


In [0]:
s=['hello Google , Hello world']

In [0]:
test1=Embedding.texts_to_sequences(s)

In [53]:
print(test1  )

[[]]


In [0]:
# More Concrete Example with Padding and other words Which arent there in the Vocab

training_data=['Sunil Gavaskar is the first batsman to score ten thousand runs','Virat is one of the fastest batsman to reach ten thousand runs']



In [0]:
TOKINIZER=Tokenizer(num_words=100 , oov_token='<OOV>')

In [56]:
TOKINIZER.fit_on_texts(training_data)
word_index=TOKINIZER.word_index
print(word_index)

{'<OOV>': 1, 'is': 2, 'the': 3, 'batsman': 4, 'to': 5, 'ten': 6, 'thousand': 7, 'runs': 8, 'sunil': 9, 'gavaskar': 10, 'first': 11, 'score': 12, 'virat': 13, 'one': 14, 'of': 15, 'fastest': 16, 'reach': 17}


In [57]:
seq=TOKINIZER.texts_to_sequences(training_data)
print(seq)

[[9, 10, 2, 3, 11, 4, 5, 12, 6, 7, 8], [13, 2, 14, 15, 3, 16, 4, 5, 17, 6, 7, 8]]


In [0]:
test_data=['ABD is the greatest entertainer in cricket']

In [0]:
results=TOKINIZER.texts_to_sequences(test_data)

In [60]:
print(results)

[[1, 2, 3, 1, 1, 1, 1]]


In [0]:
from tensorflow.keras.preprocessing.sequence import  pad_sequences

In [0]:
padded_seq=pad_sequences(seq)

In [65]:
print(padded_seq)

[[ 0  9 10  2  3 11  4  5 12  6  7  8]
 [13  2 14 15  3 16  4  5 17  6  7  8]]


In [0]:
# Sarcasm Detection using NLP
from google.colab import files

In [0]:
import pandas as pd


In [0]:
Dataframe=pd.read_json('Sarcasm_Headlines_Dataset_v2.json',lines=True)

In [74]:
Dataframe.head()

is_sarcastic  ...                                       article_link
0             1  ...  https://www.theonion.com/thirtysomething-scien...
1             0  ...  https://www.huffingtonpost.com/entry/donna-edw...
2             0  ...  https://www.huffingtonpost.com/entry/eat-your-...
3             1  ...  https://local.theonion.com/inclement-weather-p...
4             1  ...  https://www.theonion.com/mother-comes-pretty-c...

[5 rows x 3 columns]

In [79]:
Dataframe.drop(columns=['article_link'],axis=1)

is_sarcastic                                           headline
0                 1  thirtysomething scientists unveil doomsday clo...
1                 0  dem rep. totally nails why congress is falling...
2                 0  eat your veggies: 9 deliciously different recipes
3                 1  inclement weather prevents liar from getting t...
4                 1  mother comes pretty close to using word 'strea...
...             ...                                                ...
28614             1       jews to celebrate rosh hashasha or something
28615             1  internal affairs investigator disappointed con...
28616             0  the most beautiful acceptance speech this week...
28617             1  mars probe destroyed by orbiting spielberg-gat...
28618             1                 dad clarifies this not a food stop

[28619 rows x 2 columns]

In [0]:
Sentences=Dataframe['headline']

In [81]:
Sentences

0        thirtysomething scientists unveil doomsday clo...
1        dem rep. totally nails why congress is falling...
2        eat your veggies: 9 deliciously different recipes
3        inclement weather prevents liar from getting t...
4        mother comes pretty close to using word 'strea...
                               ...                        
28614         jews to celebrate rosh hashasha or something
28615    internal affairs investigator disappointed con...
28616    the most beautiful acceptance speech this week...
28617    mars probe destroyed by orbiting spielberg-gat...
28618                   dad clarifies this not a food stop
Name: headline, Length: 28619, dtype: object

In [0]:
Sentences_list=pd.Series.to_list(Sentences)

In [85]:
Sentences_list

['thirtysomething scientists unveil doomsday clock of hair loss',
 'dem rep. totally nails why congress is falling short on gender, racial equality',
 'eat your veggies: 9 deliciously different recipes',
 'inclement weather prevents liar from getting to work',
 "mother comes pretty close to using word 'streaming' correctly",
 'my white inheritance',
 '5 ways to file your taxes with less stress',
 "richard branson's global-warming donation nearly as much as cost of failed balloon trips",
 'shadow government getting too large to meet in marriott conference room b',
 'lots of parents know this scenario',
 'this lesbian is considered a father in indiana (and an amazing one at that)',
 "amanda peet told her daughter sex is 'a special hug'",
 'what to know regarding current treatments for ebola',
 "chris christie suggests hillary clinton was to blame for boko haram's kidnapping of hundreds of schoolgirls",
 'ford develops new suv that runs purely on gasoline',
 'uber ceo travis kalanick step

In [0]:
List_tokenizer=Tokenizer(num_words=1000,oov_token='<oov>')


In [87]:
List_tokenizer.fit_on_texts(Sentences_list)
word_index=List_tokenizer.word_index
print('word index:',word_index)
Sequences=List_tokenizer.texts_to_sequences(Sentences_list)
print('Sequences:',Sequences)

word index: {'<oov>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'at': 15, 'from': 16, 'about': 17, 'by': 18, 'after': 19, 'you': 20, 'this': 21, 'out': 22, 'up': 23, 'be': 24, 'as': 25, 'that': 26, 'it': 27, 'how': 28, 'not': 29, 'he': 30, 'his': 31, 'are': 32, 'your': 33, 'just': 34, 'what': 35, 'all': 36, 'who': 37, 'has': 38, 'will': 39, 'report': 40, 'into': 41, 'more': 42, 'one': 43, 'have': 44, 'year': 45, 'over': 46, 'why': 47, 'day': 48, 'u': 49, 'area': 50, 'woman': 51, 'can': 52, 's': 53, 'says': 54, 'donald': 55, 'time': 56, 'first': 57, 'like': 58, 'no': 59, 'her': 60, 'get': 61, 'off': 62, 'old': 63, "trump's": 64, 'life': 65, 'now': 66, 'people': 67, "'": 68, 'an': 69, 'house': 70, 'still': 71, 'obama': 72, 'white': 73, 'back': 74, 'make': 75, 'was': 76, 'than': 77, 'women': 78, 'if': 79, 'down': 80, 'when': 81, 'i': 82, 'my': 83, '5': 84, 'clinton': 85, 'could': 86, 'they': 87, 't

In [88]:
word_count=List_tokenizer.word_counts
print(word_count)

OrderedDict([('thirtysomething', 1), ('scientists', 103), ('unveil', 13), ('doomsday', 4), ('clock', 16), ('of', 6292), ('hair', 61), ('loss', 39), ('dem', 4), ('rep', 25), ('totally', 54), ('nails', 13), ('why', 509), ('congress', 139), ('is', 1711), ('falling', 24), ('short', 41), ('on', 2656), ('gender', 29), ('racial', 20), ('equality', 24), ('eat', 48), ('your', 667), ('veggies', 2), ('9', 131), ('deliciously', 1), ('different', 62), ('recipes', 30), ('inclement', 2), ('weather', 28), ('prevents', 5), ('liar', 6), ('from', 1329), ('getting', 211), ('to', 9096), ('work', 203), ('mother', 81), ('comes', 78), ('pretty', 111), ('close', 45), ('using', 69), ('word', 71), ("'streaming'", 1), ('correctly', 5), ('my', 315), ('white', 366), ('inheritance', 2), ('5', 315), ('ways', 124), ('file', 9), ('taxes', 17), ('with', 1956), ('less', 69), ('stress', 33), ('richard', 24), ("branson's", 1), ('global', 53), ('warming', 7), ('donation', 13), ('nearly', 39), ('as', 877), ('much', 149), ('c

In [0]:
padding=pad_sequences(Sequences,maxlen=10)

In [92]:
print(padding)

[[  0   0   1 ...   3 661   1]
 [  1  47 239 ...   1   1   1]
 [  0   0   0 ...   1 647   1]
 ...
 [629   1 335 ...   7 843   1]
 [  0   1   1 ...   1 838   1]
 [  0   0   0 ...   7 260 178]]


In [94]:
padding[0].shape


(10,)

In [95]:
padding.shape

(28619, 10)